# Generated by Django 6.0 on 2025-12-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('organization', models.CharField(max_length=200)),
                ('years', models.IntegerField()),
                ('message', models.TextField()),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
    ]
