# Generated by Django 6.0 on 2025-12-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0002_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_name', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=200)),
                ('support_type', models.CharField(max_length=50)),
                ('situation_description', models.TextField()),
                ('guardian_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('guardian_contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('informant_name', models.CharField(max_length=200)),
                ('informant_phone', models.CharField(max_length=50)),
                ('informant_relationship', models.CharField(max_length=100)),
                ('informant_remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
