# Generated by Django 6.0 on 2025-12-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0004_donation_mentorshipbooking_partnershiprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnershiprequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
